// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Outatime")>]
[<assembly: AssemblyProductAttribute("Outatime")>]
[<assembly: AssemblyDescriptionAttribute("Temporality category to map function and values changing over the time")>]
[<assembly: AssemblyVersionAttribute("1.6.0")>]
[<assembly: AssemblyFileVersionAttribute("1.6.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Outatime"
    let [<Literal>] AssemblyProduct = "Outatime"
    let [<Literal>] AssemblyDescription = "Temporality category to map function and values changing over the time"
    let [<Literal>] AssemblyVersion = "1.6.0"
    let [<Literal>] AssemblyFileVersion = "1.6.0"
